version: "3.3"

services:
  db:
    platform: linux/x86_64 # needed for mac m1
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "demo"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    command:
      - --table_definition_cache=100
      - --performance_schema=0
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    ports:
      - "3307:3306"
    expose:
      - "3307"
