name: "Main"

on:
  push:
    branches:
      - main

jobs:
  deploy-remus:
    name: Deploy Remus
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: remus
      app: rome
    secrets: inherit
