name: "PR Opened"

on:
  pull_request:
    branches:
      - "**"
    types: [opened]

jobs:
  deploy-review-remus:
    name: Deploy Remus Review
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: review-remus
      app: ${{ github.event.number }}-rome
    secrets: inherit

  deploy-review-romulus:
    name: Deploy Romulus Review
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: review-romulus
      app: ${{ github.event.number }}-rome
    secrets: inherit
