name: "PR"

on:
  pull_request:
    branches:
      - "**"
    types: [labeled, unlabeled]

jobs:
  deploy-review-remus:
    name: Deploy Remus Review
    if: contains(github.event.pull_request.labels.*.name, 'deploy-remus') == true
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: review-remus
      app: ${{ github.event.number }}-rome
    secrets: inherit

  deploy-review-romulus:
    name: Deploy Romulus Review
    if: contains(github.event.pull_request.labels.*.name, 'deploy-romulus') == true
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: review-romulus
      app: ${{ github.event.number }}-rome
    secrets: inherit

  stop-review-remus:
    name: Stop Remus Review
    if: contains(github.event.pull_request.labels.*.name, 'deploy-remus') == false
    uses: ./.github/workflows/stop-app.yml
    with:
      environment: review-remus
      app: ${{ github.event.number }}-rome
    secrets: inherit

  stop-review-romulus:
    name: Stop Romulus Review
    if: contains(github.event.pull_request.labels.*.name, 'deploy-romulus') == false
    uses: ./.github/workflows/stop-app.yml
    with:
      environment: review-romulus
      app: ${{ github.event.number }}-rome
    secrets: inherit
