name: "PR closed"

# TODO: Only if was previously created?
on:
  pull_request:
    branches:
      - "**"
    types: [closed]

jobs:
  stop-review-remus:
    name: Stop Remus Review
    uses: ./.github/workflows/stop-app.yml
    with:
      environment: review-remus
      app: ${{ github.event.number }}-rome
    secrets: inherit

  stop-review-romolus:
    name: Stop Romolus Review
    uses: ./.github/workflows/stop-app.yml
    with:
      environment: review-romolus
      app: ${{ github.event.number }}-rome
    secrets: inherit
