name: "PR"

on:
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize, labeled]

jobs:
  deploy-review-remus:
    name: Deploy Remus Review
    if: contains(github.event.pull_request.labels.*.name, 'deploy-remus') == true
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: review-remus
      app: ${{ github.event.number }}-rome
    secrets: inherit

  deploy-review-romolus:
    name: Deploy Romolus Review
    if: contains(github.event.pull_request.labels.*.name, 'deploy-romolus') == true
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: review-romolus
      app: ${{ github.event.number }}-rome
    secrets: inherit
