name: "PR"

on:
  pull_request:
    branches:
      - "**"
    # types:
    #   - opened
    #   - synchronize
    #   - reopened
    # - labeled

jobs:
  deploy-review-remus:
    name: Deploy Remus Review
    uses: ./.github/workflows/deploy-review-app.yml
    with:
      environment: review-remus
    secrets: inherit
