name: "PR"

on:
  pull_request:
    branches:
      - "**"
    # types:
    #   - opened
    #   - synchronize
    #   - reopened
    # - labeled

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
    # TODO: Build docker and publish already? => Not money relevant

  deploy-review-remus:
    name: Deploy Remus Review
    environment: review-remus
    env:
      PR_NUMBER: ${{ github.event.number }}
      TENANT: ${{ vars.TENANT}}
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      tf_version: "1.5.7"
      tg_version: "0.53.2"
      working_dir: "infrastructure"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Setup terragrunt
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: "hclfmt --terragrunt-check --terragrunt-diff"

      # TODO: Extract
      - name: Prepare Review App
        run: |
          - export SERVICE_NAME=i--$TENANT--$PR_NUMBER-org-service
          - export ECR=i-$TENANT-$PR_NUMBER-org-ecr
          - export CLUSTER_NAME=i--$TENANT--$PR_NUMBER-org-cluster
          - export FRONTEND_DESTINATION_BUCKET=s3://i--$TENANT_SLUG--$PR_NUMBER-org-frontend-bucket
          - cd infrastructure/tenants
          - mkdir $PR_NUMBER
          - cp $TENANT/terragrunt.hcl $PR_NUMBER/terragrunt.hcl
          - cd $PR_NUMBER
          - terragrunt plan --terragrunt-non-interactive

          - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/$ECR
          - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/$ECR:latest -f backend/Dockerfile ./backend
          - docker push $AWS_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/$ECR:latest
          - >
            aws ecs update-service --cluster $CLUSTER_NAME
            --service arn:aws:ecs:eu-central-1:$AWS_ACCOUNT_ID:service/$SERVICE_NAME
            --region eu-central-1
            --force-new-deployment > /dev/null

        # TODO: Build frontend for specific tenant
        #   - aws s3 sync frontend/dist $FRONTEND_DESTINATION_BUCKET --delete
